---
version: "2.0"

services:
  app:
    image: alikarim/akash:v2.0
    env:
      - SSH_PUBLIC_KEY=<content of the ssh public key>
    expose:
      - port: 80
        to:
          - global: true
      - port: 2022
        as: 2022
        to:
          - bastion
  bastion:
    image: alikarim/akash-bastion:v2.0
    env:
      - SSH_USER=akuser
      - SSH_PUBLIC_KEY=<content of the ssh public key>
    expose:
      - port: 2022
        as: 2022
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    bastion:
      resources:
        cpu: 
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 128Mi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        app: 
          denom: uakt
          amount: 100
        bastion: 
          denom: uakt
          amount: 100

deployment:
  app:
    akash:
      profile: app
      count: 1
  bastion:
    akash:
      profile: bastion
      count: 1
