---
version: "2.0"

services:
  app:
    image: {{APP_IMAGE}}
    env:
      - SSH_PUBLIC_KEY={{SSH_PUBLIC_KEY}}
    expose:
      - port: 80
        to:
          - global: true
      - port: {{SSH_PORT}}
        as: {{SSH_PORT}}
        to:
          - bastion
  bastion:
    image: {{BASTION_IMAGE}}
    env:
      - SSH_USER={{SSH_USER}}
      - SSH_PUBLIC_KEY={{SSH_PUBLIC_KEY}}
    expose:
      - port: {{SSH_PORT}}
        as: {{SSH_PORT}}
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    bastion:
      resources:
        cpu: 
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 128Mi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        app: 
          denom: uakt
          amount: 100
        bastion: 
          denom: uakt
          amount: 100

deployment:
  app:
    akash:
      profile: app
      count: 1
  bastion:
    akash:
      profile: bastion
      count: 1
